export type Variant = {
    color: string
    images: string[]
}

export type Product = {
    id: string
    serial: string
    status: string
    title: string
    subtitle: string
    image: string
    images: string[]
    price: string
    action: string
    section: "accessories" | "apparel"
    color: string
    variants?: Variant[]
    sizes?: string[]
    description: string[]
    details: string[]
    sizeChart?: string
}

export const allProducts: Product[] = [
    {
        id: "1",
        serial: "AR-15-X-HYPER",
        status: "ARMED",
        title: "ADVANCED STRIKE AR-15",
        subtitle: "Kinetic Precision Platform",
        image: "/merch/rifle.png",
        images: ["/merch/rifle.png"],
        price: "14,200.00",
        action: "ACQUIRE",
        section: "accessories",
        color: "#1a1a1a",
        description: [
            "Mil-spec upper and lower receiver.",
            "Match-grade trigger assembly.",
            "30-round capacity magazine included.",
            "Made in the USA.",
        ],
        details: [
            "Caliber: 5.56×45mm NATO",
            "Barrel length: 16 inches",
            "Overall length: 32.5 inches",
            "Weight: 6.8 lbs unloaded",
            "Rail system: M-LOK handguard",
            "Finish: Matte black anodized",
        ],
    },
    {
        id: "7",
        serial: "TS-KF-001",
        status: "IN STOCK",
        title: "TSALLA KEY FOB",
        subtitle: "Aerospace-Grade Accessory",
        image: "/merch/hatsss.png",
        images: ["/merch/hatsss.png"],
        price: "35.00",
        action: "ACQUIRE",
        section: "accessories",
        color: "#1a1a1a",
        description: [
            "CNC-machined aerospace aluminum.",
            "Laser-engraved Tsalla Aerospace logo.",
            "Anodized matte black finish.",
            "Made in the USA.",
        ],
        details: [
            "Material: 6061-T6 Aluminum",
            "Dimensions: 2.5 × 1.2 × 0.3 inches",
            "Weight: 0.8 oz",
            "Finish: Type III Hardcoat anodize",
            "Hardware: Stainless steel split ring",
        ],
    },
    {
        id: "8",
        serial: "TS-HAT-001",
        status: "IN STOCK",
        title: "TSALLA HAT",
        subtitle: "Structured Technical Cap",
        image: "/merch/hat1.png",
        images: ["/merch/hat1.png", "/merch/hat2.png"],
        price: "55.00",
        action: "ACQUIRE",
        section: "accessories",
        color: "#1a1a1a",
        sizes: ["S/M", "L/XL"],
        description: [
            "Structured 6-panel construction.",
            "Embroidered Tsalla Aerospace logo.",
            "Moisture-wicking sweatband.",
            "Made in the USA.",
        ],
        details: [
            "Material: 100% Cotton twill",
            "Closure: Adjustable snapback",
            "Profile: Mid-crown structured",
            "Embroidery: 3D puff on front",
            "Brim: Flat, pre-curved option",
        ],
    },
    {
        id: "2",
        serial: "TFJ-M-001",
        status: "LIMITED",
        title: "TSALLA HOODIE",
        subtitle: "Mission-Grade Flight Apparel",
        image: "/merch/hoodie11.png",
        images: ["/merch/hoodie11.png", "/merch/hoodie12.png"],
        price: "1,850.00",
        action: "ACQUIRE",
        section: "apparel",
        color: "#1A43BF",
        variants: [
            { color: "#1A43BF", images: ["/merch/hoodie11.png", "/merch/hoodie12.png"] },
            { color: "#000000", images: ["/merch/hoodie1.png", "/merch/hoodie2.png"] },
        ],
        sizes: ["Small", "Medium", "Large", "XL", "2XL", "3XL"],
        description: [
            "Ultra-high-density technical fleece construction.",
            "Reinforced elbow panels for durability.",
            "Adjustable storm-hood with internal mesh lining.",
            "Stealth-integrated Kangaroo pocket with zipper locks.",
            "Made in the USA.",
        ],
        details: [
            "Shell: 480 GSM Cotton/Poly Heavy Fleece",
            "Reinforcements: Cordura® elbow patches",
            "Lining: Breathable aerospace mesh hood lining",
            "Hardware: Matte black zinc-alloy aglets",
            "Fit: Relaxed mission-profile cut",
            "Feature: Integrated thumb-loop cuffs",
        ],
    },
    // {
    //     id: "3",
    //     serial: "TFJ-W-001",
    //     status: "LIMITED",
    //     title: "TSALLA FLIGHT JACKET (WOMEN)",
    //     subtitle: "Mission-Grade Flight Apparel",
    //     image: "/merch/womenjacket.png",
    //     images: ["/merch/womenjacket.png"],
    //     price: "5,400.00",
    //     action: "ACQUIRE",
    //     section: "apparel",
    //     color: "#0d0d0d",
    //     sizes: ["Small", "Medium", "Large", "XL", "2XL", "3XL"],
    //     description: [
    //         "Shell: Water-repellent polyester.",
    //         "Premium YKK zip front closure.",
    //         "Knit collar, cuffs and waistband.",
    //         "Snap pocket closures.",
    //         "Zippered map/pencil pocket on bicep.",
    //         "Includes mission patches and flight tag.",
    //     ],
    //     details: [
    //         "Shell: 100% Water-repellent polyester",
    //         "Lining: 100% Nylon",
    //         "Fill: Thermolite® insulation",
    //         "Closure: YKK #10 coil zipper",
    //         "Pockets: 4 exterior, 2 interior",
    //         "Patches: Embroidered mission set included",
    //     ],
    // },
    // {
    //     id: "4",
    //     serial: "RS-MEN-001",
    //     status: "LIMITED",
    //     title: "TSALLA SHIRT (MEN)",
    //     subtitle: "Limited Collaboration — Men's",
    //     image: "/merch/mens.png",
    //     images: ["/merch/mens.png"],
    //     price: "220.00",
    //     action: "ACQUIRE",
    //     section: "apparel",
    //     color: "#0d0d0d",
    //     sizes: ["Small", "Medium", "Large", "XL", "2XL"],
    //     description: [
    //         "Exclusive Reyn Spooner® x Tsalla Aerospace collab.",
    //         "All-over engineered botanical-aerospace print.",
    //         "Classic camp collar construction.",
    //         "Mother-of-pearl buttons.",
    //         "Made in Hawaii, USA.",
    //     ],
    //     details: [
    //         "Shell: 100% Cotton spooner kloth™",
    //         "Fit: Relaxed / classic camp",
    //         "Collar: Convertible camp collar",
    //         "Buttons: Mother-of-pearl",
    //         "Pocket: Single chest utility",
    //         "Print: Engineered botanical-aerospace",
    //     ],
    // },
    // {
    //     id: "5",
    //     serial: "RS-WMN-001",
    //     status: "LIMITED",
    //     title: "REYN SPOONER® x TSALLA SHIRT (WOMEN)",
    //     subtitle: "Limited Collaboration — Women's",
    //     image: "/merch/women.png",
    //     images: ["/merch/women.png"],
    //     price: "220.00",
    //     action: "ACQUIRE",
    //     section: "apparel",
    //     color: "#0d0d0d",
    //     sizes: ["XS", "Small", "Medium", "Large", "XL"],
    //     description: [
    //         "Exclusive Reyn Spooner® x Tsalla Aerospace collab.",
    //         "All-over engineered botanical-aerospace print.",
    //         "Slightly fitted feminine silhouette.",
    //         "Mother-of-pearl buttons.",
    //         "Made in Hawaii, USA.",
    //     ],
    //     details: [
    //         "Shell: 100% Cotton spooner kloth™",
    //         "Fit: Semi-fitted / feminine cut",
    //         "Collar: Convertible camp collar",
    //         "Buttons: Mother-of-pearl",
    //         "Pocket: Single chest utility",
    //         "Print: Engineered botanical-aerospace",
    //     ],
    // },
    {
        id: "6",
        serial: "TS-UNI-001",
        status: "IN STOCK",
        title: "TSALLA SHIRT (UNISEX)",
        subtitle: "Core Collection Tee",
        image: "/merch/shirt1.png",
        images: ["/merch/shirt1.png", "/merch/shirt2.png"],
        price: "95.00",
        action: "ACQUIRE",
        section: "apparel",
        color: "#000000",
        sizes: ["XS", "Small", "Medium", "Large", "XL", "2XL"],
        description: [
            "Premium heavyweight cotton construction.",
            "Embroidered Tsalla Aerospace chest logo.",
            "Ribbed crew neck collar.",
            "Unisex relaxed fit.",
            "Made in the USA.",
        ],
        details: [
            "Material: 100% Combed ring-spun cotton",
            "Weight: 6.5 oz / sq yd",
            "Collar: Ribbed crew neck",
            "Logo: Left chest embroidery",
            "Fit: Unisex relaxed",
            "Care: Machine wash cold, tumble dry low",
        ],
    },
    {
        id: "9",
        serial: "TS-UNI-001",
        status: "IN STOCK",
        title: "TSALLA BAT (UNISEX)",
        subtitle: "Core Collection Tee",
        image: "/merch/bat-1.jpg",
        images: ["/merch/bat-1.jpg", "/merch/bat-2.jpg"],
        price: "95.00",
        action: "ACQUIRE",
        section: "apparel",
        color: "#000000",
        sizes: ["XS", "Small", "Medium", "Large", "XL", "2XL"],
        description: [
            "Premium heavyweight cotton construction.",
            "Embroidered Tsalla Aerospace chest logo.",
            "Ribbed crew neck collar.",
            "Unisex relaxed fit.",
            "Made in the USA.",
        ],
        details: [
            "Material: 100% Combed ring-spun cotton",
            "Weight: 6.5 oz / sq yd",
            "Collar: Ribbed crew neck",
            "Logo: Left chest embroidery",
            "Fit: Unisex relaxed",
            "Care: Machine wash cold, tumble dry low",
        ],
    },
    {
        id: "10",
        serial: "TS-UNI-001",
        status: "IN STOCK",
        title: "TSALLA FENIX (UNISEX)",
        subtitle: "Core Collection Tee",
        image: "/merch/fenix-1.jpg",
        images: ["/merch/fenix-1.jpg", "/merch/fenix-2.jpg"],
        price: "95.00",
        action: "ACQUIRE",
        section: "apparel",
        color: "#000000",
        sizes: ["XS", "Small", "Medium", "Large", "XL", "2XL"],
        description: [
            "Premium heavyweight cotton construction.",
            "Embroidered Tsalla Aerospace chest logo.",
            "Ribbed crew neck collar.",
            "Unisex relaxed fit.",
            "Made in the USA.",
        ],
        details: [
            "Material: 100% Combed ring-spun cotton",
            "Weight: 6.5 oz / sq yd",
            "Collar: Ribbed crew neck",
            "Logo: Left chest embroidery",
            "Fit: Unisex relaxed",
            "Care: Machine wash cold, tumble dry low",
        ],
    },
    {
        id: "11",
        serial: "TS-UNI-001",
        status: "IN STOCK",
        title: "TSALLA Black shirt (UNISEX)",
        subtitle: "Core Collection Tee",
        image: "/merch/black.png",
        images: ["/merch/black.png"],
        price: "95.00",
        action: "ACQUIRE",
        section: "apparel",
        color: "#000000",
        sizes: ["XS", "Small", "Medium", "Large", "XL", "2XL"],
        description: [
            "Premium heavyweight cotton construction.",
            "Embroidered Tsalla Aerospace chest logo.",
            "Ribbed crew neck collar.",
            "Unisex relaxed fit.",
            "Made in the USA.",
        ],
        details: [
            "Material: 100% Combed ring-spun cotton",
            "Weight: 6.5 oz / sq yd",
            "Collar: Ribbed crew neck",
            "Logo: Left chest embroidery",
            "Fit: Unisex relaxed",
            "Care: Machine wash cold, tumble dry low",
        ],
    },
    {
        id: "12",
        serial: "TS-UNI-001",
        status: "IN STOCK",
        title: "TSALLA White Shirt (UNISEX)",
        subtitle: "Core Collection Tee",
        image: "/merch/white2.png",
        images: ["/merch/white2.png"],
        price: "95.00",
        action: "ACQUIRE",
        section: "apparel",
        color: "#000000",
        sizes: ["XS", "Small", "Medium", "Large", "XL", "2XL"],
        description: [
            "Premium heavyweight cotton construction.",
            "Embroidered Tsalla Aerospace chest logo.",
            "Ribbed crew neck collar.",
            "Unisex relaxed fit.",
            "Made in the USA.",
        ],
        details: [
            "Material: 100% Combed ring-spun cotton",
            "Weight: 6.5 oz / sq yd",
            "Collar: Ribbed crew neck",
            "Logo: Left chest embroidery",
            "Fit: Unisex relaxed",
            "Care: Machine wash cold, tumble dry low",
        ],
    },

]